repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.52.0
    hooks:
      - id: eslint
        files: \.js$ # or .ts, .jsx, etc

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.1.0"]
        files: \.js$ # or .ts, .jsx, etc
        args:
          - --write
          - --ignore-unknown
