name: Build, test and publish

on: push

permissions:
  id-token: write
  contents: read

jobs:
  build12:
    uses: ./.github/workflows/build.yaml
    with:
      oarepo: "12"

  publish:
    runs-on: ubuntu-latest
    needs: build12
    steps:
      - name: Use built artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: List files
        run: |
          ls -la
          ls -la dist

      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install ESLint config
        run: npm install --no-save --no-package-lock @inveniosoftware/eslint-config-invenio@^2.0.0

      - name: Run ESLint
        run: npx eslint .
